import "./globals.css";
import { TaskProvider } from "../context/taskContext.jsx";
import Navbar from "@/components/Navbar";
import { Toaster } from "./Toaster";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-darkBlue">
        <TaskProvider>
          <Navbar />
          {children}
          <Toaster />
        </TaskProvider>
      </body>
    </html>
  );
}
